// <auto-generated />
namespace itransition_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IssueFixing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IssueFixing));
        
        string IMigrationMetadata.Id
        {
            get { return "201605012200306_IssueFixing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
